/*
Each new term in the Fibonacci sequence is 
generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms 
will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence 
whose values do not exceed nth term, find the sum 
of the even-valued terms.

*/


function fiboEvenSum(n) {
  let a = 1;
  let b = 2;
  let sumEvens = b; // b is even

  // i start form 2 cus first term and second term
  // defined outside the loop
  for (let i=2; i<n; i++){
    let next = a + b;

    sumEvens += (next % 2) === 0 ? next : 0;

    a = b;
    b = next;
  }

  return sumEvens;
}
